import React from 'react';
import { library } from '@fortawesome/fontawesome-svg-core';
import {
	// faLightbulbOn,
	// faFileInvoice,
	// faFileContract,
	// faCogs,
	// faMoneyBill,
	// faBadgeDollar,
	// faList,
	// faFunnelDollar,
	// faMobile,
	// faWindowAlt,
	// faUsers,
	// faChartPie,
	// faBuilding,
	// faHandshake,
	// faClipboard,
	// faClipboardListCheck,
	// faChartLine,
	// faChartNetwork,
	// faLink,
	// faUserChart,
	// faLaptopCode,
	// faPhoneOffice,
	// faHandsUsd,
	// faAward,
	// faCommentAltEdit,
	// faCalendarEdit,
	// faClipboardCheck,
	// faWaveformPath,
	// faPencilRuler,
	// faFileCheck,
	// faUserHeadset,
	// faListAlt,
	// faPollH,
	// faSmile,
	// faStar,
	// faTasks,
	// faThumbsUp,
	// faMegaphone,
	// faMailBulk,
	// faAnalytics,
	// faTrophyAlt,
	// faAbacus,
	// faHandHoldingSeedling,
	// faCommentAltSmile,
	// faGlobe,
	// faCommentsAlt,
	// faCommentAltDots,
	// faCommentDiagrams,
	// faProjectDiagram,
	// faReply,
	// faTags,
	// faCalendarDay,
	// faSeedling,
	// faChalkboardTeacher,
	// faCreditCard,
	// faTruck,
	// faClock,
	// faUserHardHat,
	// faCalendarStar,
	// faCalendarCheck,
	// faFileSearch,
	// faSpiderWeb,
	// faIdCard,
	// faDesktop,
	// faSortAmountUpAlt,
	// faHandsHelping,
	// faBusinessTime,
	// faHeadset,
	// faPortalExit,
	// faFileUser,
	// faFileChartPie,
	// faBrowser,
	// faWandMagic,
	// faRocketLaunch,
	// faMedal,
	// faStore,
	faPhoneAlt,
	faArrowLeft,
	faArrowRight,
	faShoppingCart,
	faQuoteRight,
	faUserTie,
	faUserHeadset,
	faHandHoldingBox,
	faTruckContainer,
	faBoxAlt,
	faBurgerSoda,
	faCannabis,
	faTruckCouch,
	faAmbulance,
	faDollyFlatbed,
	// faWallet,
	// faUserCheck,
	// faAddressBook,
	// faHandReceiving,
	// faPhonePlus,
	// faSquare,
	// faSackDollar,
	// faSearchLocation,
	// faDatabase,
	// faSave,
	// faBinoculars,
	// faDebug,
	// faCompass,
	// faShieldCheck,
	// faSearch,
	// faKey,
	// faVolumeMute,
	// faMobileAndroid,
	faHandHoldingSeedling,
	faConciergeBell,
	faEnvelopeOpenDollar,
	faStar,
} from '@fortawesome/pro-duotone-svg-icons';
import {
	faFacebookSquare,
	faTwitterSquare,
	faInstagramSquare,
	faYoutubeSquare,
	faLinkedin,
} from '@fortawesome/free-brands-svg-icons';

import { CssBaseline, MuiThemeProvider } from '@material-ui/core';
import theme from '../../theme';

import { Nav } from './Nav';
import { Footer } from './Footer';
import 'typeface-poppins';

library.add(
	// 	faLightbulbOn,
	// 	faFileInvoice,
	// 	faFileContract,
	// 	faCogs,
	// 	faMoneyBill,
	// 	faBadgeDollar,
	// 	faList,
	// 	faFunnelDollar,
	// 	faMobile,
	// 	faWindowAlt,
	// 	faUsers,
	// 	faChartPie,
	// 	faBuilding,
	// 	faHandshake,
	//   faClipboard,
	// 	faClipboardListCheck,
	// 	faChartLine,
	// 	faChartNetwork,
	// 	faLink,
	// 	faUserChart,
	// 	faLaptopCode,
	// 	faPhoneOffice,
	// 	faHandsUsd,
	// 	faAward,
	// 	faCommentAltEdit,
	// 	faCalendarEdit,
	// 	faClipboardCheck,
	// 	faWaveformPath,
	// 	faPencilRuler,
	// 	faFileCheck,
	// 	faUserHeadset,
	// 	faListAlt,
	// 	faPollH,
	// 	faSmile,
	// 	faStar,
	// 	faTasks,
	// 	faThumbsUp,
	// 	faMegaphone,
	// 	faMailBulk,
	// 	faAnalytics,
	// 	faTrophyAlt,
	// 	faAbacus,
	// 	faHandHoldingSeedling,
	// 	faCommentAltSmile,
	// 	faGlobe,
	// 	faCommentsAlt,
	// 	faCommentAltDots,
	// 	faProjectDiagram,
	// 	faReply,
	// 	faTags,
	// 	faCalendarDay,
	// 	faSeedling,
	// 	faChalkboardTeacher,
	// 	faCreditCard,
	// 	faTruck,
	// 	faClock,
	// 	faUserHardHat,
	// 	faCalendarStar,
	// 	faCalendarCheck,
	// 	faFileSearch,
	// 	faSpiderWeb,
	// 	faIdCard,
	// 	faDesktop,
	// 	faSortAmountUpAlt,
	// 	faHandsHelping,
	// 	faBusinessTime,
	// 	faHeadset,
	// 	faPortalExit,
	// 	faFileUser,
	// 	faFileChartPie,
	// 	faBrowser,
	// 	faWandMagic,
	// 	faRocketLaunch,
	// 	faMedal,
	// 	faStore,
	faFacebookSquare,
	faTwitterSquare,
	faInstagramSquare,
	faYoutubeSquare,
	faLinkedin,
	faPhoneAlt,
	faArrowLeft,
	faArrowRight,
	faShoppingCart,
	faQuoteRight,
	faHandHoldingSeedling,
	faConciergeBell,
	faEnvelopeOpenDollar,
	faStar,
	faUserTie,
	faUserHeadset,
	faHandHoldingBox,
	faTruckContainer,
	faBoxAlt,
	faBurgerSoda,
	faCannabis,
	faTruckCouch,
	faAmbulance,
	faDollyFlatbed
	// faWallet,
	// faUserCheck,
	// faAddressBook,
	// faHandReceiving,
	// faPhonePlus,
	// faSquare,
	// faSackDollar,
	// faSearchLocation,
	// faDatabase,
	// faSave,
	// faBinoculars,
	// faDebug,
	// faCompass,
	// faShieldCheck,
	// faSearch,
	// faKey,
	// faVolumeMute,
	// faMobileAndroid,
);

export const Layout = ({ children }) => {
	return (
		<MuiThemeProvider theme={theme}>
			<CssBaseline />
			<Nav />
			{children}
			<Footer />
		</MuiThemeProvider>
	);
};
